---
env:
  node: true

parserOptions:
  ecmaVersion: 2018
  sourceType: module

extends:
  - eslint:recommended
  - plugin:import/errors
  - plugin:import/warnings

rules:
  no-console: off
  no-extra-semi: off
