os: linux
distro: trusty

sudo: required

services:
  - docker

addons:
  apt: {packages: [docker-ce]}

env:
  global:
    - LOCAL_NAME=hybsearch
    - DEST_NAME=docker.io/hybsearch/hybsearch
    - GIT_TAG="$TRAVIS_TAG"
    - GIT_BRANCH="$TRAVIS_BRANCH"
    - GIT_SHA="$TRAVIS_COMMIT"

before_script:
  # - if [[ -e ~/docker/image.tar ]]; then docker load -i ~/docker/image.tar; fi
  - docker build --rm=false -t "$LOCAL_NAME" .
  # - mkdir -p ~/docker; docker save "$LOCAL_NAME" > ~/docker/image.tar

stages:
  # - prepare
  - test
  - deploy

jobs:
  include:
    # "prepare" just builds and caches the Docker image for us
    - stage: prepare
      env: [TASK=prepare]
      script: skip

    # check that the whole pipeline runs at all
    - stage: test
      env: [TASK=worker-runner]
      script: docker run -i --entrypoint /hybsearch/scripts/worker-runner.js "$LOCAL_NAME" - < data/emydura-short.gb

    # test ent.js against all our sample files
    - stage: test
      env: [TASK=test-ent]
      script: docker run --entrypoint /hybsearch/scripts/test-ent.sh "$LOCAL_NAME"

    # deploy the docker images to Docker Hub
    - stage: deploy
      env: [TASK=deploy]
      script:
        - image_id="$(docker images -q "$LOCAL_NAME")"
        - |
          if [[ $TRAVIS_BRANCH == master ]]; then
            docker_tag="$DEST_NAME:HEAD"
          else if [[ $TRAVIS_TAG ]]; then
            docker_tag="$DEST_NAME:$TRAVIS_TAG"
          else if [[ $TRAVIS_BRANCH ]]; then
            docker_tag="$DEST_NAME:$TRAVIS_BRANCH"
          fi
        - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
        - docker tag "$image_id" "$docker_tag"
        - docker push "$docker_tag"
        - |
          if [[ $TRAVIS_TAG ]]; then
            docker tag "$image_id" "$DEST_NAME:latest"
            docker push "$DEST_NAME:latest"
          fi

cache:
  directories:
   - ~/docker
