os: linux
distro: trusty
sudo: required

services:
  - docker

addons:
  apt:
    packages:
      - docker-ce

before_install:
  - docker build -t hybsearch .

script:
  - docker run hybsearch node /hybsearch/scripts/worker-runner.js
