os: linux
distro: trusty
sudo: required

services:
  - docker

addons:
  apt:
    packages:
      - docker-ce

before_install:
  - docker build -t hybsearch .

script:
  - docker run hybsearch /bin/sh -c "node ./scripts/worker-host-test.js"
