os: linux
distro: trusty
sudo: required

services:
  - docker

addons:
  apt:
    packages:
      - docker-ce

before_install:
  - docker build -t hybsearch/hybsearch .

script:
  - docker run hybsearch/hybsearch /bin/sh -c "node ./scripts/worker-runner.js"
