os: osx
osx_image: xcode8.3
language: node_js
node_js: '8'

env:
  global:
    # prevent brew from updating itself automatically
    - HOMEBREW_NO_AUTO_UPDATE=1

before_install:
  - brew update

install:
  - brew list
  - brew install homebrew/science/beagle --with-opencl
  - brew install open-mpi

script:
  - python2 ./vendor/seqmagick/cli.py convert --input-format fasta --output-format nexus --alphabet dna data/emydura.fasta output/emydura.nexus
  - node ./scripts/worker-host-test.js
