os: linux
distro: trusty
sudo: required

services:
  - docker

addons:
  apt:
    packages:
      - docker-ce

before_install:
  - docker build -t docker.io/hybsearch/hybsearch .

script:
  - docker run docker.io/hybsearch/hybsearch /bin/sh -c "node ./scripts/worker-host-test.js"
