---
version: 2

x-config:
  - &name "hybsearch/hybsearch"
  - &defaults
    docker:
      - image: circleci/node:8-stretch
    environment: &default-environment
      LOCAL_NAME: *name
      DEST_NAME: docker.io/hybsearch/hybsearch
  - &caches
    npm-load: &cache-load-npm
      keys:
        - npm--{{ arch }}-{{ checksum "package-lock.json" }}
    npm-save: &cache-save-npm
      key: npm--{{ arch }}-{{ checksum "package-lock.json" }}
      paths:
        - ./node_modules
        - ./node-modules-was-cached
    docker-load: &cache-load-docker
      keys:
        - docker--{{ arch }}-{{ .Branch }}
        - docker--{{ arch }}
    docker-save: &cache-save-docker
      key: docker--{{ arch }}-{{ .Branch }}
      paths:
        - /tmp/image.tar.gz
    docker-load-cmd: &cmd-docker-load
      name: 'Load from cache if possible'
      command: |
        if test -r /tmp/image.tar.gz; then
          echo "Loading from /tmp/image.tar.gz"
          docker load -qi /tmp/image.tar.gz
        else
          echo "missing /tmp/image.tar.gz; continuing with build"
        fi
    docker-save-command: &cmd-docker-save
      name: 'Dump image to cachable .tar.gz file'
      command: docker save "$LOCAL_NAME:$CIRCLE_SHA1" | pigz -9c > /tmp/image.tar.gz

workflows:
  version: 2
  on_commit:
    jobs:
      - cache
      - build: {requires: [cache]}
      - lint: {requires: [cache]}
      - test-js: {requires: [cache]}
      - test-worker: {requires: [build]}
      - deploy-docker: {requires: [test-worker, test-js]}
      - deploy-github: {requires: [test-worker, test-js]}

  cron_weekly:
    triggers:
      - schedule:
          # only run Monday morning at 12:00am
          cron: 0 0 * * 1
          filters:
            branches:
              only: [master]
    jobs:
      - cache
      - build: {requires: [cache]}
      - test-js: {requires: [cache]}
      - test-worker: {requires: [build]}

jobs:
  # cache node_modules
  cache:
    <<: *defaults
    steps:
      - checkout
      - restore_cache: *cache-load-npm
      - run: '[ -f ./node-modules-was-cached ] || sudo npm i -g npm'
      - run: '[ -f ./node-modules-was-cached ] || npm ci'
      - run: '[ -f ./node-modules-was-cached ] || touch ./node-modules-was-cached'
      - save_cache: *cache-save-npm

  # build the docker image
  build:
    <<: *defaults
    steps:
      - checkout
      - setup_remote_docker
      - restore_cache: *cache-load-npm
      - run: {name: 'List docker images', command: 'docker images -a'}
      - run:
          name: 'Build docker image'
          command: docker build --cache-from="$(docker images -a -q)" -t "$LOCAL_NAME:$CIRCLE_SHA1" .
      - run: sudo apt install -y pigz
      - run: *cmd-docker-save
      - save_cache: *cache-save-docker

  # run sanity checks
  lint:
    <<: *defaults
    steps:
      - checkout
      - restore_cache: *cache-load-npm
      - run: npm run eslint

  # check that the whole pipeline runs at all
  test-worker:
    <<: *defaults
    steps:
      - checkout
      - setup_remote_docker
      - restore_cache: *cache-load-docker
      - run: *cmd-docker-load
      - run: docker run -i --entrypoint /hybsearch/scripts/run-worker.js "$LOCAL_NAME:$CIRCLE_SHA1" - < data/emydura-short.gb

  # test ent.js against all our sample files
  test-js:
    <<: *defaults
    steps:
      - checkout
      - restore_cache: *cache-load-npm
      - run: npm test

  # deploy the docker images to Docker Hub
  deploy-docker:
    <<: *defaults
    steps:
      - checkout
      - setup_remote_docker
      - restore_cache: *cache-load-docker
      - run: *cmd-docker-load
      - run: docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
      - run:
          name: Push to Docker Hub
          command: |
            image_id="$(docker images -q "$LOCAL_NAME:$CIRCLE_SHA1")"
            echo "image_id: $image_id"

            echo "CIRCLE_BRANCH: $CIRCLE_BRANCH" "CIRCLE_TAG: $CIRCLE_TAG"
            if [[ $CIRCLE_BRANCH = master ]]; then
              docker_tag="$DEST_NAME:HEAD"
            elif [[ $CIRCLE_TAG ]]; then
              docker_tag="$DEST_NAME:$CIRCLE_TAG"
            elif [[ $CIRCLE_BRANCH ]]; then
              docker_tag="$DEST_NAME:$CIRCLE_BRANCH"
            fi
            echo "docker_tag: $docker_tag"

            docker tag "$image_id" "$docker_tag"
            docker push "$docker_tag"

            if [[ $CIRCLE_TAG ]]; then
              docker tag "$image_id" "$DEST_NAME:latest"
              docker push "$DEST_NAME:latest"
            fi

  # deploy the compiled electron binaries to GitHub Releases
  deploy-github:
    <<: *defaults
    docker:
      - image: electronuserland/builder:wine
    steps:
      - checkout:
          path: /root/project
      - run: npm i -g npm
      - run: npm i -g electron-builder
      - run: npm ci
      - run: npm run build
